// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahptvqriffkizhmsjiel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocHR2cXJpZmZraXpobXNqaWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTI0NjQsImV4cCI6MjA3MjQyODQ2NH0.W9eK_BxGmG8A8aCDDH-Yx4DJ7E6B5xFU900QhVXK8Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});